version: "3"
services:
  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_USER=lhc
      - MYSQL_PASSWORD=123456
      - MYSQL_DATABASE=lhc
    networks:
      app_net:
        ipv4_address: 10.10.10.2
    container_name: "compose-mysql"
  php:
    image: bitnami/php-fpm
    ports:
      - "9000:9000"
    volumes:
      - "$PWD/html:/var/www/html"
    networks:
      app_net:
        ipv4_address: 10.10.10.3
    container_name: "compose-php"
  nginx:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - "mysql"
      - "php"
    volumes:
      - "$PWD/conf.d:/etc/nginx/conf.d"
      - "$PWD/html:/usr/share/nginx/html"
      - "$PWD/html:/var/www/html"
    networks:
      app_net:
        ipv4_address: 10.10.10.4
    container_name: "compose-nginx"
networks:
  app_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.0.0/16
